language: android
android:
  components:
    - build-tools-20.0.0
    - android-L
    - sys-img-x86-android-tv-l
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

env:
  global:
    - TERM=dumb

notifications:
  email: false

after_success:
- ./gradlew :inject-plugin:jacocoTestReport :inject-plugin:coveralls

