/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the extra data it found.  It
 * should not be modified by hand.
 */

package com.test.injectextra;

public final class R {
    public static final class array {
        public static final int array1=0x7f080001;
        public static final int intarray1=0x7f080000;
    }
    public static final class attr {
    }
    public static final class bool {
        public static final int bool1=0x7f040000;
    }
    public static final class color {
        public static final int color1=0x7f050000;
        public static final int colorlist=0x7f050001;
    }
    public static final class dimen {
        public static final int dimen1=0x7f060000;
    }
    public static final class integer {
        public static final int integer1=0x7f070000;
    }
    public static final class raw {
        public static final int small=0x7f020000;
    }
    public static final class string {
        public static final int string1=0x7f030000;
    }
}
